### ISSUE TITLE
GitHub no longer supports this web browser. 

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#144]
We must be concerned that Mypal is no longer supported by GitHub.

**Comment by ByRodrigoSoares** [comment]
Some solution for this incompatibility in a new version ??

**Comment by RAD750** [comment]
The only "fix" that seems to be needed is adding another override for Github
In: `general.useragent.override.github.com` I put:
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:72.0) Gecko/20100101 Firefox/72.0`

And site seems to work:
![image](https://user-images.githubusercontent.com/12469744/75752168-6f8fee00-5d28-11ea-96da-4ef898163910.png)

**Comment by ByRodrigoSoares** [comment]
I did this procedure but it didn't solve

**Comment by RAD750** [comment]
Could you provide a screenshot and a description of what you were doing to get the problem? I have been browsing since yesterday on Github and the message never appeared again after applying the fix. Maybe try clearing cache and cookies or doing a force refresh (CTRL+SHIFT+R)?

**Comment by ByRodrigoSoares** [comment]
I already did the procedure mentioned above, I cleared the cache, but here the message continues

![cats](https://user-images.githubusercontent.com/50956690/75995135-be7d8500-5eda-11ea-9bc0-d83d0f0909d8.jpg)

**Comment by RAD750** [comment]
It did appear briefly for me, but after logging in the message was cleared and never appeared again. Maybe try that while I am investigating the matter?
I will keep you updated ;)

**Comment by ByRodrigoSoares** [comment]
Thanks grateful for the attention I am waiting for some solution

**Comment by RAD750** [comment]
So after further investigation it would appear that the banner is not generated by the server, but by a script served by `githubassets.com`(using eMatrix and blocking scripts from that domain fixed the issue). Adding an override for that domain didn't fix the issue.
As of right now I am unable to confirm which script is responsible, but I have a suspicion it is this one: 
`https://github.githubassets.com/assets/unsupported-bootstrap-9a3d052e.js`

My knowledge of Javascript is very poor so I am unfortunately unable to provide a solution because I don't know how the script detects the browser version without user agent.

I also tried setting the user agent override globally, but to no avail.

Anyway the banner doesn't prevent you from using the site at all, and if you login it will disappear for good.
I hope someone with better knowledge of JS than me can help fix this issue :)

**Comment by Feodor2** [comment]
I have examined the matter and say you are right about this script. It unhides the banner, the trigger is "undefined" == typeof **customElements** which my pal does not have. This means if ms intentionally put in their scripts **customElements** functions mypal will be fail to work properly.
 I don't know why customElements would be necessary and shall examione further.

**Comment by Feodor2** [comment]
Well original palemoon affected too and its developers are aware
https://forum.palemoon.org/viewtopic.php?f=3&t=23611&hilit=customElements

**Comment by ByRodrigoSoares** [comment]
> 
> 
> I already did the procedure mentioned above, I cleared the cache, but here the message continues
> 
> ![cats](https://user-images.githubusercontent.com/50956690/75995135-be7d8500-5eda-11ea-9bc0-d83d0f0909d8.jpg)

**Thank you MyPal team this message no longer appears in this new version**

**Comment by IP-CAM** [comment]
> In: general.useragent.override.github.com I put: .....
Where and how did you achieve this, I cannot find any file in MyPal, to be edited that way ...

**Comment by ByRodrigoSoares** [comment]
> 
> 
> > In: general.useragent.override.github.com I put: .....
> > Where and how did you achieve this, I cannot find any file in MyPal, to be edited that way ...

**The problem has already been solved in this new version, the message no longer appears**

**Comment by RAD750** [comment]
For future reference @IP-CAM , you should put the string in the about:config page (right click -> add new string)

**Comment by IP-CAM** [comment]
Thanks a lot ! Just tell me, of the value needs to be true or false.
Sorry, after trying to get fluent with OpenCart's Secrets for the past 6 Years, I have a hard time sometimes, to recall much more simpler Things.  Or then, I just too old for that sh... already .
