### ISSUE TITLE
Problem with rendering some fonts in MyPal

### ISSUE THREAD

**Issue by Enersil** [Feodor2/Mypal#17]
WinXP SP3
New Moon 27.5.1 32b, that is all right:
https://i4.imageban.ru/out/2018/10/15/64a1930db83d8232eb0346deb45ffb10.jpg

MyPal 28.1.0 32b, rough fonts:
https://i4.imageban.ru/out/2018/10/15/137e202186a0408caad614cabb2233ea.jpg

**Comment by Feodor2** [comment]
Well i see screenshots certainly letters bad, provide links to that page.

Straight away i can say that all modern fonts is shown bad because dirext2d missing on winxp, another font system is to develop for replacement.

**Comment by Enersil** [comment]
gfx.canvas.azure.backends: it was before "direct2d1.1,skia,cairo", now "direct2d1.1,cairo".
gfx.content.azure.backends: it was before "direct2d1.1,direct2d,cairo", now "direct2d1.1,cairo".
Not help.
But in "New Moon 27.5.1", 32b, WinXP SP3 - smooth fonts, no additional settings.

**Comment by kitaro1** [comment]
Disable hardware acceleration in the options.
After removing, skia I have nice and thin fonts in palemoon 28.1, basilisk 55, firefox 52.9.
Font Arial Narrow :)
[URL=https://www.fotosik.pl/zdjecie/13f46773cb93b66b][IMG]https://images92.fotosik.pl/57/13f46773cb93b66b.png[/IMG][/URL]

**Comment by Feodor2** [comment]
First: i took 27.5.1 and opened my test page on local machine where modern fonts is used, since you not provide the link to your page. And what i see - the same stunted letters.

Second: i build mypal without skia code for a long time, when i found it bad on winxp, so skia has no use whatever is set in settings. By the way direct2d1 has no use too, and this is the problem. To be sure open the same page on the newer windows and you will have normal letters.

And last: I want to develop new code for replacing direct2d1, however it demand great effort and many free time, so i wont say when even i shall done this. Meanwhile i have good workaround - replace modern fonts with its regular versions, there where converters i know - install fonts to you winxp system - restrict downloading of modern fonts by noscript or other means.

**Comment by kitaro1** [comment]
No!
Mypal28.1 gfx.canvas.azure.backends (string) direct2d1.1,skia,cairo
http://prntscr.com/l7eslv
gfx.canvas.azure.backends (string) direct2d1.1,cairo
http://prntscr.com/l7esu3
URL - http://alltube.pl/filmy-online/wersja[Lektor,Dubbing]+kategoria[5]+strona[2]+

**Comment by Enersil** [comment]
For example, a page about the addon "uBlockOrigin" on the reddit.com.
https://www.reddit.com/r/uBlockOrigin/
New Moon 27.5.1 - smooth fonts, MyPal 28.1.0 rough fonts.

**Comment by Enersil** [comment]
On https://www.youtube.com "rough' time under the time line:
https://imageban.ru/show/2018/10/19/000a6039bb7a390e5c6ba687c009c8d6/jpg

**Comment by kitaro1** [comment]
Some websites are not allowed to use other fonts.
Reddit has a stupid code.
http://prntscr.com/l7uyok

**Comment by AroKol78** [comment]
#266
