### ISSUE TITLE
No Extension works in version 29.9.2

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#175]
**This version will really have to be recompiled has many problems**

**Comment by joeturnes** [comment]
After installing this latest 29.9.2  32 bit version, i lost all my windows & tabs from prev 29.9.1 session. & my extensive bookmarks toolbar was "hiding". May have been switched with the navigation toolbar that i always hide. Luckily, everything was good again when I went back to 29.9.1.  Phew! From now on, I'm bookmarking tabs asap & keeping as few open as possible. & waiting for Mypal to tell me an update is avail(& not automatically installing it either, rather than just habitually looking in 
https://github.com/Feodor2/Mypal/releases , trying to get the newest release b4 everyone else. lol
& also checking in the forum for problems with latest release, b4 installing.

**Comment by Feodor2** [comment]
The fail in 28.9.2 update, i am making next update asap,
