### ISSUE TITLE
Default browser not setting

### ISSUE THREAD

**Issue by gdl-888** [Feodor2/Mypal#208]
Tested on Windows XP, Vista(with admin privileges), 7 with Mypal 28.10.0. When I start the browser, it asks if I want to use it as a default browser. I clicked yes, but it keeps asking to set to default browser. I set it as a default program in the control panel, but it does not recognize it.

**Comment by fastnetcom** [comment]
https://github.com/Feodor2/Mypal27old/wiki/Portable

**Comment by kitaro1** [comment]
Mypal portable cannot remember the default browser setting. Each new launch of Mypal is a new message about setting Mypal as the default browser.
Mypal is no longer useful on windows 7. The unique options appdata and local appdata in the program folder are kept by iceveasel 77.0.1. Higher versions of iceveasel slow down the cursor and writing posts. This is how Mozilla perfected and so you have to suffer.

**Comment by Feodor2** [comment]
It sets the default browser but window keeps poping up, indeed a bug, i shall fix it on the next release, until this remove checkbox in always check...

**Comment by kitaro1** [comment]
> 
> 
> It sets the default browser but window keeps poping up, indeed a bug, i shall fix it on the next release, until this remove checkbox in always check...

The browser does not remember the settings, but the system remembers file types. http://prnt.sc/texkfq

**Comment by WavySwirlz** [comment]
This has been a bug since as long as I can remember, as far as I know.

I wonder if it relates to the 'Such a portable, no-remote' option (which as a native English/UK speaker, I can tell you makes literally no sense) option in the installer - which on a non-portable install does seem to do absolutely nothing.

There's usually an option in Mozilla-based browsers' setup script/UI to set whatever you're installing as the default one before you do the first launch... Mypal lacks this, however there's an option labelled 'Such a portable, default browser feature disabled' (which btw, is worded extremely poorly...) which could be somehow broken?

**Comment by gdl-888** [comment]
Sounds right, I didn't mind the text "default browser feature disabled", because I was using custom installation, and that checkbox was a subcomponent of the "portable" radio.

**Comment by Feodor2** [comment]
28.11.0 will be today and there the bug was fixed.

**Comment by Feodor2** [comment]
Hi WavySwirlz, suggest better words for that, i am not native english at all.

As for portable, as i know it should not embed in a system in any way, but many users want underportable or semiportable, correct me which is right, that's why i have made it optional.

**Comment by WavySwirlz** [comment]
@Feodor2 Perhaps something like: 'Disable all system association functionality (fully portable)'

You're welcome. :3

**Comment by gdl-888** [comment]
the problem is solved, thanks

**Comment by Feodor2** [comment]
@ghost
Good, i shall change words on next release
