### ISSUE TITLE
MPL 2.0 commented

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal#22]
> Q6: I want to distribute software which is available under the MPL, either changed or unchanged, within my organization. What do I have to do?
> 
> **Nothing.** The right to private modification and distribution (and inside a company or organization counts as 'private') is another right guaranteed by free and open source software licenses, including the MPL.

@Feodor2 is not Organization but Moonchild.

> Q17: What does "distribute" mean?
> 
> The MPL uses "distribute" in the sense of ****delivery** of a copy** of the software to another person or entity. **We do not use distribute to mean "make available"** in the sense of "making functionality available over the web without delivery of a copy of the software." So e.g. in a web-based application, the code which runs on the server is not 'distributed' to the user, but the code which is sent to the client (e.g. HTML, CSS, JavaScript) does count as 'distributed'.

So, you may restore repos without negative actions, because this repo never breaks MPL 2.0.

**Comment by Feodor2** [comment]
The problem was about i did not put proper links to the source, i did not understand importance of this, and they utilized this to remove me from the development, but only me, other may continue, but should take with great care.
So this things above irrelevant.

**Comment by Anbima** [comment]
@Feodor2
Try to agree with Pale Moon and supplement the missing data in the new version. MyPal is the only usable browser for a lot of Windows XP users.

It would be very important to us that you continue to develop it.

**Comment by JeanPaulLucien** [comment]
> The problem was about i did not put proper links to the source, i did not understand importance of this, and they utilized this to remove me from the development, but only me, other may continue, but should take with great care.
> So this things above irrelevant.

You **should not**. Also 5.1 does not require to delete an executable files and source code in public resources. You have the rights to restore all.

As you see, Moonchild does not anwser to me, because there is no arguments to answer. He knows.

**Comment by hockeymikey** [comment]
You should continue development of it @Feodor2

**Comment by ROBERT-MCDOWELL** [comment]
I agree, @Feodor2, they cannot do anything against you, you didn't break the MPL license and if the issue comes
from the links you didn't put so put these links back and everything is ok.

**Comment by Feodor2** [comment]
I think continue work with paleomoon will be a waste for me, even if i could make few updates. But you still may use my latest version it will be actual for some time
I try to make new winxp browser not related to the palemoon in any way.

**Comment by ROBERT-MCDOWELL** [comment]
@Feodor2 right, anyhow there are always solution in computer world ;)

**Comment by ByRodrigoSoares** [comment]
> Acho que continuar trabalhando com paleomoon será um desperdício para mim, mesmo que eu pudesse fazer poucas atualizações. Mas você ainda pode usar minha versão mais recente, ela será real por algum tempo.
> Eu tento fazer um novo navegador winxp não relacionado ao palemoon de forma alguma.

An alternative would be to use Mozilla's own Seamonkey browser as a base.

**Comment by enigma9o7** [comment]
Right now it seems source code for mypal is unavailable.  I assume it has to be made available upon request by anyone with binary if it is not already publicly available.  I have binary @Feodor2 so you please post source code publically to avoid being in violation of any licenses.  This website (github) is good for that.

**Comment by AroKol78** [comment]
the code was removed due to alleged MPL breaking.
three gentlemen came and demanded that the source code be removed
https://github.com/Feodor2/Centaury/issues/41
https://github.com/Feodor2/Centaury/issues/40
https://github.com/Feodor2/Centaury/issues/39

by the way, I recommend reading all #3 "license" for a better understanding of the situation
you can read them here
https://www.reddit.com/r/palemoon/comments/pexate/pale_moon_developers_abuse_mozilla_public_license/
https://www.reddit.com/r/opensource/comments/pf6hyd/pale_moon_developers_abuse_mozilla_public_license/

**Comment by LaOrhyUAcMji** [comment]
This whole incident is ridiculous to me, license issues aside, it seems like the PaleMoon dev team is hell-bent on attacking their own supporters (and people forking PaleMoon for XP -are- supporters of the PM project, one would have to be autistic to think otherwise).

Anyway, not here for mud-slinging, just wanted to say @Feodor2 thank you so much for developing this browser. Given the country you're in, it's quite possible that you can continue development without any real repercussions. There are also many channels other than Github to publish your releases.

**Comment by JeanPaulLucien** [comment]
@Feodor2 ты видишь, что лицензия требует удаления программного обеспечения и кода после окончания прав? Ага. **Нет там такого** требования. 

Удалить установщики и исходные код - это только твоё решение,

**Comment by ROBERT-MCDOWELL** [comment]
@Feodor2
a famous XP related websites where you can also send the binaries and the sources of course! :D
https://xpforever.miraheze.org/wiki/Main_Page

**Comment by sskras** [comment]
@Feodor2, I ask you for some more details. You wrote:

> The problem was about i did not put proper links to the source, i did not understand importance of this, 

That's understandable. 
Intellectual Property and Licensing is quite unintuitive stuff.

Did you fix the links to reflect the actual source code afterwards?

If you did, the license requirements are fulfilled again. And you again would become compliant.

> and they utilized this to remove me from the development, 

From what I have read, they just demanded that. 
They are not judges at court to remove anyone from anything.

I guess, they aren't even lawyers. And even if they are, they should send you official letter to prove they are sincere and not trolling.

So they only expressed their demand based on their legal interpretation (which might be right).

My next text will depend on your response to my first question. Thanks in advance :)

**Comment by Feodor2** [comment]
> If you did, the license requirements are fulfilled again. And you again would become compliant.

Of course next i'll watch it carefully.

> From what I have read, they just demanded that.

Remove contributions mean that (5p of the license)

> If you did, the license requirements are fulfilled again. And you again would become compliant.

Without these contributions the stuff become fully useless, i go forward instead ahere to useless junk.

**Comment by sskras** [comment]
Umm. So have you fixed the URLs to point to **Mypal** source code ever? Yes or no? :)

**Comment by AroKol78** [comment]
removal request, not repair url https://github.com/Feodor2/Centaury/issues/39

the whole story of the dispute https://github.com/Feodor2/Mypal/issues/11#issue-985640067

**Comment by sskras** [comment]
@AroKol78, a bit TL;DR except for:

> removal request

_Removal_ here sounds too bold and isn't explicitly defined by the MPL-2.0 (as far as I can see):

> > 5.1. The rights granted under this License will terminate automatically if You fail to comply with any of its terms.

What could be stopped are following rights / grants:
(we ignore patent stuff as non-relevant for this case)

> > [...] the rights granted under this License from a particular Contributor [...]
  ...
> > **2.1. Grants**
> > [...] a world-wide, royalty-free, non-exclusive license:
> > 
> > **(a)** [...] to use, reproduce, make available, modify, display, perform, distribute, and otherwise exploit its Contributions, either on an unmodified basis, with Modifications, or as part of a Larger Work; and

I translate this as stopping distribution in binary form. 
And only starting since `2021-08-24T03:54:57Z`, when the so-called rights terminator* expressed the personal demand.
And the source lines to be removed should be originating only from that person.

---

\* Who speaking strictly yet remains to be physically identified + verified in the issue because of lack of the physical document one should have sent to you. And one which might be just a scammer -- how do we know some nick on GitHub is the real contributor?

IMNSHO this wouldn't work in the court without expression of a will in a physical form (eg. mail/letter).

But it's up to @Feodor2 to believe whether it's the real contributor.

**Comment by AroKol78** [comment]
I'm not a lawyer - so I don't know
many people have already discussed this topic (https://github.com/Feodor2/Mypal/issues/11#issue-985640067)

https://github.com/Feodor2/Mypal/issues/22#issuecomment-917097998 - everything is clear to me

**Comment by sskras** [comment]
I see a way to go forward with the contributions in this repository until that date.
I see current state as bad because:

(1) now I have have an older binaries but cannot see how exactly they work.
(2) now volunteers cannot be sure from which commit to start resuming the development.
(And whether something still remains to be cleaned up)

The first one would be a violation of MPL-2.0 on its own.
Only that we are not that mad to make hysteria around this. :)

I case of @Feodor2 I would:

0. Export the current (three) commits from my current empty (new) dir into some `temp-dir`:
`git format-patch HEAD^^^...HEAD -o temp-dir`
2. `cd` into my original working (old) dir.
3. Reset the commits **newer** than the termination date (if any):
`git reset --hard <LAST_COMMIT_SHA_ID_UNTIL_20210824_03:54:57Z>`
3. Remove the asked source code + commit this:
`git commit -a -m "Removal of code from grants terminator Name Surname (under request)"`
4. Publish the remaining, earlier commits here by overwriting the three commits in currently almost empty repo:
`git push --force`
5. Truncate the old `README.md`;
6. Merge the three patches from the step 0 on top of the old content:
`git am .../temp-dir/000*.patch`
7. Push them into the remote repo too.

Then to be safe:

8. [Create a new organization](https://github.com/settings/organizations) dedicated to the code (eg. `Mypal-org`) here on GitHub.
9. [Move the repo there](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account).
10. Open the issue to call for new contributors.
11. Add them as owners/maintainers of the new organization.
12. Remove yourself from it.

That would be a real, graceful termination of your activities. :)

13. Receive regards from fans and future contributors of `Mypal`.
14. Start working on your own, totally unrelated fork!

PS. I am willing to assist you with that (and I can speak Russian in case this helps).

EDIT: Some small mistakes + added the source removal step.

**Comment by Feodor2** [comment]
@sskras
Look links in https://github.com/Feodor2/Mypal/issues/11#issuecomment-912717073 there all tags for older binaries and volunteers can resuming the development from the last commit. No commits are newer than the termination date
Also what is a point to create dedicated organization?

> And one which might be just a scammer -- how do we know some nick on GitHub is the real contributor?

What is a point? He is he can sure prove, and the issue is already resolved.

**Comment by sskras** [comment]
> Look links in [#11 (comment)](https://github.com/Feodor2/Mypal/issues/11#issuecomment-912717073) there all tags for older binaries and volunteers can resuming the development from the last commit. No commits are newer than the termination date

Thanks for clarification.

> Also what is a point to create dedicated organization?

To keep the repository alive (including the closed issues) + to be able to disassociate it from your personal ownership.

> > And one which might be just a scammer -- how do we know some nick on GitHub is the real contributor?
> 
> What is a point? He is he can sure prove,

Being emotionally sure is not enough when we enter the Legal area. Law has its' own requirements. Ones coming to my mind straight away:

(1) The removal requirement should be physical, documental; 
(2) The claimant/plaintiff should identify himself physically.

What if that's some hacker who took over that account & is just trying to ruin peace inside F/LOSS world (using legal trolling) ?
Trust no one in the world of Law. That's what I wanted to deliver in my comments.

> and the issue is already resolved.

Your decision to solve the issue was overkill, IMO -- you deleted too much. :)

Which created another issue: now any remaining Mypal users are denied an access to the source code (and the older Wiki URLs) which already was there and could have remained that way (minus the lines/files required for removal).
(See `git blame ...`)

The right way to solve would have been to remove the required code.

But as you seem to avoid doing this, I am eager to go that route instead of you. : P
I would create mentioned organization if you agree to transfer your repo to it.
M?

**Comment by Feodor2** [comment]
> you deleted too much.

It may be, but this is done now, old repo has been deleted.

> Which created another issue: now any remaining Mypal users are denied an access to the source code (and the older Wiki URLs)

I not allowed provide the source, but others can access it already, including you, from malepoon and others, though i may restore that one old wiki.

> (See git blame ...)

Whats with it?

> I would create mentioned organization if you agree to transfer your repo to it.

Sure if you want, do you want to become a succesor? Let it be this new repo for a checkpoint and reminder. Transfer question was about old repo till it had all stuff, today it is not actual.

**Comment by sskras** [comment]
@Feodor2:
> > Which created another issue: now any remaining Mypal users are denied an access to the source code (and the older Wiki URLs)
> 
> I not allowed provide the source, but others can access it already, including you, from malepoon and others, 

(I just do some nitpicking, no offense)

I got this information just because you said it here / someone wrote it in another ticket.
But the right way would be through seeing these URLs in the running program itself.
So this remains to be fixed.

> though i may restore that one old wiki.

It would be very nice. Now only to decide whether you should put it here or in another new repo.

> > (See git blame ...)
> 
> Whats with it?

If the commit process was done right (the `Author: ...` lines are correct), then it [shows whom which lines of code](https://linuxhint.com/git_blame/#:~:text=git%20blame%20window) does belong to.
And doing `grep` for that angry guy would reveal the exact lines necessary to remove. 

> > I would create mentioned organization if you agree to transfer your repo to it.
> 
> Sure if you want, do you want to become a succesor? 

Yes and no.
Yes, I would like to have the owner (an organization) of the source being independent from a single person.
Then no, I would not have enough time to maintain it.

I haven't build it even once.
Then there is a question left regarding hosting binaries for downloading.

> Let it be this new repo for a checkpoint and reminder. 
> Transfer question was about old repo till it had all stuff, today it is not actual.

Umm, OK. But this new (if you say so) repo still has older Wiki pages, eg:
[История что и как](https://github.com/Feodor2/Mypal/wiki/%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F-%D1%87%D1%82%D0%BE-%D0%B8-%D0%BA%D0%B0%D0%BA)

So I thought it's an old repo. If it's new repo, are you able to transfer them to another repos?

And do you mean the old issues are gone?

**Comment by Feodor2** [comment]
> And doing grep for that angry guy would reveal the exact lines necessary to remove.

Let put aside that angry guy had uploaded whole firfox source, so it would reveal that all lines necessary to remove. Okey you have removed several lines, whats next?

> Yes, I would like to have the owner (an organization) of the source being independent from a single person.

Why, does an orgnization may not include only one person? Why do you care at all, if you not going to use this article.

> And do you mean the old issues are gone?

No, i have saved some i though useful.
