### ISSUE TITLE
Old font problem on winXP

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#266]
blurred font
http://spacesimcentral.com/
https://www.eso.org/public/news/?lang

**Comment by ghost** [comment]
> 
> 
> blurred font
> http://spacesimcentral.com/
> https://www.eso.org/public/news/?lang

http://prnt.sc/uux538
You can download the fonts and add whatever you want. Whatever you set, the same you have. Deselect the one shown in the screenshot.
Many pages have unclear fonts.

**Comment by AroKol78** [comment]
Partial solution to the problem (sometimes letters are too small or overlap).
Similar result at 120% zoom.

**Comment by Feodor2** [comment]
http://spacesimcentral.com/
Not blurred but uncomfortable for reading, in the 360chrome it is the same.
https://www.eso.org/public/news/?lang
Yes, bad font is "Helvetica Neue LT ESO" 

Block fonts from web and make substitute, i remember i did this i shall write the knowhow.

**Comment by AroKol78** [comment]
http://spacesimcentral.com/
![fontsScale](https://user-images.githubusercontent.com/70756447/95665162-f83bfb80-0b4d-11eb-9bfe-9a4b1d928a20.JPG)
120% = twice the zoom
res 1440x900
to block the display of fonts > browser.display.use_document_fonts 0

**Comment by AroKol78** [comment]
sometimes letters are too small or overlap  =  browser.display.use_document_fonts 0
simple info https://browser.taokaizen.com/chrome-directwrite/
winxp has a problem because there is no direct2d

**Comment by Feodor2** [comment]
## Inspect element of the page

Right click on the bad font and choose  Inspect element
![image](https://user-images.githubusercontent.com/19492771/97759693-99e1b780-1b12-11eb-8e5e-7f5b992c6181.png)

Look above for **class** word.
![image](https://user-images.githubusercontent.com/19492771/97759950-25f3df00-1b13-11eb-8526-310bb844377f.png)

Copy the value by right click
![image](https://user-images.githubusercontent.com/19492771/97760092-6f442e80-1b13-11eb-9db0-b4c95355c4fe.png)

## UserContent.css

Close browser, open profile folder and look for **chrome** folder inside, if it is no such folder create it, There is a file UserContent.css, create it if not exists. Add to the file this below, set font-family and size values you want and save the file.
```
@-moz-document domain("spacesimcentral.com") {
.entry-content {font-family: Verdana !important;
  font-size: 150% !important;
 }
}
```
## Second site
![image](https://user-images.githubusercontent.com/19492771/97760743-eded9b80-1b14-11eb-971b-45161a764f1b.png)

```
@-moz-document domain("www.eso.org") {
.news-teaser {font-family: Arial !important;
  font-size: 120% !important;
 }
}
```

**Comment by AroKol78** [comment]
Magician.
I had no idea about such possibilities.
For the future I will know what to do.
I found better:
**.entry-content**  to  **#page**
**.news-teaser**    to  **#body**
Thanks.

**Comment by AroKol78** [comment]
@spyrosmas (from https://github.com/gorhill/uBlock-for-firefox-legacy/issues/305#issuecomment-848899291)
> "Allow pages to choose their own fonts, instead of my selections above" must be checked for power button to draw correctly, but this has side effect that some sites like outlook.live.com and many others display their own version of fonts; eg. italics in sign up form or draw whole pages with Times New Roman which is crap left from ancient calligraphy times.

if the page has a wrong font, I change the font appropriate for a specific page in file **UserContent.css**
example
```
/*
 *  FIX FONTS
 */

@-moz-document domain("spacesimcentral.com") {
#page {font-family: Verdana !important;
  font-size: 100% !important;
 }
}

@-moz-document domain("www.eso.org") {
#body {font-family: Arial !important;
  font-size: 120% !important;
 }
}
```

**Comment by spyrosmas** [comment]
The problem with UserContent.css specific solutions like http://www.floppymoose.com/ and others is that they require too much quirk code and maintenance to overcome what "Allow pages to choose their own fonts, instead of my selections above" setting does with just one click. With UserContent.css remote fonts will continue to download and render inside a browser, (which is also a memory hog and security risk) and even worse, when the webpage author changes the name of .news-teaser to something else, UserContent.css needs inspection and correction once again.

The UserContent.css solution is only worth for 1 or 2 domains and only for debugging css. In a general case, who going to write thousands of lines for every possible domain when most web developers use some kind of monkey automation tool which write most of web pages with too large fonts or too blurry or too small or with wrong font kerning?

It seems that those who dictate internet had lost common sense (even if they had any) and more important they had allergy to the truth.
Anyway, thanks for the info.

**Comment by AroKol78** [comment]
**ubo** "You can prevent web fonts from being downloaded"...
info https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts
