### ISSUE TITLE
yahoo email

### ISSUE THREAD

**Issue by Elizabeth1623** [Feodor2/Mypal#29]
version 27.9.4, xppro sp3, when I sign into 2 of my yahoo email accounts, the page is there for approx one second and disappears, my avatar is there but nothing else. when I sign into my other 2 accounts the problem does not occur.

can get into all 4 in firefox 52.9.0ESR no problem,

thanks for any assistance. :)

**Comment by wyxchari** [comment]
Yes, I confirm the problem. It has not failed me before because I use yahoo classic mail.
![screenshot - 31_08_2018 07_05_53](https://user-images.githubusercontent.com/42490583/44893771-192d9380-acdc-11e8-9ce4-831d57aaac30.jpg)

**Comment by letmeindude** [comment]
Feodor2, are we going to see MyPal v28?

**Comment by wyxchari** [comment]
@Elizabeth1623 Run Firefox, switch to the classic Yahoo mail in the configuration wheel on the right, close Firefox and open Mypal, which will come out with classic mail while the problem is fixed.

**Comment by Tony0945** [comment]
I had trouble logging in to yahoo recently. Like you, Firefox was okay. Googling found this tip on the Palemoon forum:
Change the default useragent for yahoo (general.useragent.override.yahoo.com)  to:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8" without the quotes. It sounds nuts for a PC running XP but it works!
I suspect that yahoo is trying to deliberately block XP because I did not have to do this on Linux, only XP. Didn't try win 7.

**Comment by wyxchari** [comment]
Optimized:
about:config
general.useragent.override.yahoo.com
Just add at end: Version/10.1.2 Safari/603.3.8

**Comment by Elizabeth1623** [comment]
wyxchari, yes that worked now I see the emails in both of the accounts that were blank before, thanks :)
