### ISSUE TITLE
Can you port this browser for Windows 2000?

### ISSUE THREAD

**Issue by kweonsunho** [Feodor2/Mypal#309]
Few browsers can work properly for Windows 2000. Can you port this browser for Windows 2000? Then it will be a great browser on Windows 2000 as well.

**Comment by Feodor2** [comment]
I would like but it is no time to do for this is not important for me.

**Comment by roytam1** [comment]
> Few browsers can work properly for Windows 2000. Can you port this browser for Windows 2000? Then it will be a great browser on Windows 2000 as well.

better installing extended kernel instead. my NM26-vc8 build may be the latest browser on 2000 without extended kernel.

**Comment by ClassicNick** [comment]
I have tried to compile Mypal 28.9.1 on Visual C++ 2008, but it can only get past configure with the option --disable-compile-environment. Once I try building the source code, it takes ~5 minutes to land on the browser directory, and it does that because it seems to only read the jar.mn files and copy the files it reads from the jar.mn files to the obj-i686-pc-mingw32\dist\bin directory, resulting in an obviously broken build. My other build tools are Mozilla-Build 2.2, and the Windows 7 SDK, and I use Windows XP SP3 to build. This issue will have to be fixed before it is reasonably possible to build Mypal on Windows 2000.

**Comment by Feodor2** [comment]
Many cpp files also must to be changed according  Visual C++ 2008 specifications. Also some windows api functions which win2000 do not have.

**Comment by ClassicNick** [comment]
Very true, I tried compiling Firefox 31.8.0esr on Visual C++ 2008, and I gave up before I even got past the mfbt directory. On your MinGW32 build of Mypal, you link to MSVCR100.dll. What kind of compilation errors would linking to MSVCR90.dll produce? On my Visual C++ 2010 build of New Moon 26, I got a runtime error "DecodePointer could not be located in the dynamic link library KERNEL32.dll".
