### ISSUE TITLE
Support subforum possibly?

### ISSUE THREAD

**Issue by ghost** [Feodor2/Mypal#327]
Hey,
the creator of the Vista extended kernel (win32) and my close friend @R3n001 (_mwahh_ uwu) own a forum here: https://forum.eclipse.cx/index.php - also available over http and loads well on older systems/browsers, intentionally.

Perhaps could be made as the 'official' home for mypal support forums as a subforum there? We really appreciate yours and rt1's works, unlike the official PM team who I'm sorry you got hit by - Tobin is a narcissistic prick, Moonchild too, it's yours and others' project that actually makes their browser relevant lol, they should be grateful but nope lol.

I'm sort of a representative of the eclipse forums but also not, I'm doing this as a kind gesture for you and r3n really because well why not? :3

~compadesudesu

**Comment by Compadesudesu** [comment]
@roytam1 this will also apply to your browser series - we can provide a subforum there for 'official' support, unlike long abandoned MSFN forums who only care about maintenance when their advertising network bugs them to do things

**Comment by roytam1** [comment]
> MSFN forums who only care about maintenance

but at least their moderators do moderating job well.
for me, I hope I can just post new release notes, and answering users' questions, and users peer-helping each others, are good to me. and at least, MSFN has such atmosphere at the moment.

**Comment by Compadesudesu** [comment]
"but at least their moderators do moderating job well."

There's someone there who has an obvious alt account and isn't banned (Dixel/D.Draker), for a start... on a side note, the fact the site was broken with adblock off for so long, and that it took the staff over two weeks or so to notice the forum update broke the registration form, really says a lot about the management... Personally, I feel like if the moderators truly cared about doing more than banning people who shared any modified MS files and spambots every now and again (and even that has been less than satisfactory lately), they'd have given you a subforum already and cleaned up a lot of the inactive projects.

A single thread for your hefty browser platform, not sure what to label it otherwise, feels like an insult to your contributions personally over there given it's one of the only active threads on the entire MSFN board nowadays :/

I'm glad you're in support of the idea, personally I feel that MSFN is basically on life support and mainly is only active from a few specific threads and the fact there's basically almost nnowhere else to go, excluding MyDigitalLife which requires login to see anything useful (and promotes activation cracking, which isn't something welcomed over at Eclipse, we'd shoot things like that down if seen/mentioned)

**Comment by AroKol78** [comment]
`https://github.com/Eclipse-Community/forum` **read-only ?**

`https://github.com/Eclipse-Community/forum/issues/2`
**Remove displayed IP addresses -  Open ?**

**Comment by Compadesudesu** [comment]
@AroKol78 That's from before the usage of phpBB, we were going to use some ancient mess of a forum software customised, but decided against it.

**Comment by AroKol78** [comment]
forum yes - if safe (e.g. not ip leaks)
not all are experienced with using vpn / proxy / set user agent override /.../...

**Comment by AroKol78** [comment]
the forum is the least of the problems
you want to help - you can write source codes - then fix known bugs

**Comment by R3n001** [comment]
> 
> 
> forum yes - if safe (e.g. not ip leaks)
> not all are experienced with using vpn / proxy / set user agent override /.../...

People can't really discover where you live from an IP, at most they'd just get the location the ISP is at. So, it's not really worth it for hackers to target IP leaks. I just wanted to prevent myself from accidentally leaking a IP shown on a post when screenshotting a post and sending the image somewhere. The issue was inadvertently fixed by switching to phpBB, as IP addresses are more hidden.

**Comment by R3n001** [comment]
> There's someone there who has an obvious alt account and isn't banned (Dixel/D.Draker), for a start... 

Well, my forum doesn't ban alt accounts, and even has an extension that allows linking two forum accounts to allow for quick switching between the two accounts. However, if two accounts that get banned have the same IP address, there will be an IP ban.

> (and promotes activation cracking, which isn't something welcomed over at Eclipse, we'd shoot things like that down if seen/mentioned)

Only for legal reasons.

**Comment by Compadesudesu** [comment]
@AroKol78 It was suggested after Moonchild and his heavy, the New Tobin Paradigm, decided to cause drama over the existence of this project and roytam1's one.

Also, code skills aren't required to contribute to a project. How many projects have so many great coders behind them on the low-level side of things, yet have a lack of people able to update the documentation or graphical presentation, as well as a lack of decent 'public relations' like say, a support forum or such? Quite a lot, and it mostly affects the FOSS community.

**Comment by Feodor2** [comment]
@Compadesudesu
If offer the forum is for free i will be glad of course do it.

**Comment by R3n001** [comment]
> 
> 
> @Compadesudesu
> If offer the forum is for free i will be glad of course do it.

It's for free.

**Comment by R3n001** [comment]
> > MSFN forums who only care about maintenance
> 
> but at least their moderators do moderating job well.
> for me, I hope I can just post new release notes, and answering users' questions, and users peer-helping each others, are good to me. and at least, MSFN has such atmosphere at the moment.
> 
> (P.S.: I'm not against your idea, for clarification)

This is probably too much to ask, but it would really help grow the forum if you moved exclusively to forum.eclipse.cx, and left a link to the Eclipse thread on MSFN.

**Comment by roytam1** [comment]
> This is probably too much to ask, but it would really help grow the forum if you moved exclusively to forum.eclipse.cx, and left a link to the Eclipse thread on MSFN.

will think about it if I'm comfortable to do my tasks in your forum

**Comment by R3n001** [comment]
> 
> 
> I registered already - name Theodor

Forgot to tell you that you have a Mypal topic on the forum now. A description is coming when I quit being lazy and busy.

**Comment by Feodor2** [comment]
Great, i learn rules meanwhile.
