### ISSUE TITLE
nbcnews webpages come up & then quickly go blank!

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#401]
Neither
general.useragent.override.nbcnews.com
Mozilla/5.0 (Windows NT 5.1; rv:99.9) Gecko/20100101 Firefox/99.9
nor
general.useragent.override.nbcnews.com
Mozilla/5.0 (Windows NT 5.1; rv:78.0) Gecko/20100101 Firefox/78.0
in about:config
made a difference.

**Comment by AroKol78** [comment]
the problem is with the scripts from adobedtm
ubo -> my filters add
`||assets.adobedtm.com^$script,domain=nbcnews.com,important`
,important it must be because "EasyPrivacy" is allowed

(see https://github.com/Feodor2/Mypal/issues/402 `||assets.adobedtm.com^$script,domain=oracle.com|nbcnews.com,important`)

**Comment by joeturnes** [comment]
Thanks, AroKol78 - nbcnews.com pages now remain visible!
I also tried the above with acmemarkets.com but still no good with that website - some sort of blasted script is running & locks up browser - must be a different problem. Ridiculous. lol
